// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package module

import (
	"wire/event"
)

// Injectors from wire.go:

func InitializeEvent() *event.Event {
	message := event.NewMessage()
	greeter := event.NewGreeter(message)
	eventEvent := event.NewEvent(greeter)
	return eventEvent
}
